import type { WordPack } from './types'

export const WORD_PACKS: WordPack[] = [
  {
    id: 'cibo',
    name: 'Cibo e bevande',
    entries: [
      { word: 'Pizza', clue: 'Si condivide in tavola' },
      { word: 'Carbonara', clue: 'Ci vuole una ricetta' },
      { word: 'Gelato', clue: 'Meglio in estate' },
      { word: 'Caffè', clue: 'Questione di abitudine' },
      { word: 'Sushi', clue: 'Arriva da lontano' },
      { word: 'Panettone', clue: "Torna una volta all'anno" },
      { word: 'Birra', clue: 'Si beve in compagnia' },
      { word: 'Nutella', clue: 'Crea dipendenza' },
      { word: 'Insalata', clue: 'Fa bene, dicono' },
      { word: 'Lasagna', clue: 'Meglio della nonna' },
      { word: 'Popcorn', clue: 'Fa rumore' },
      { word: 'Cornetto', clue: 'Roba da mattina presto' },
      { word: 'Peperoncino', clue: 'Non per tutti' },
      { word: 'Vino', clue: 'Migliora col tempo' },
      { word: 'Kebab', clue: 'Cibo da notte fonda' },
    ],
  },
  {
    id: 'animali',
    name: 'Animali',
    entries: [
      { word: 'Gatto', clue: 'Fa quello che vuole' },
      { word: 'Cane', clue: 'Ti aspetta a casa' },
      { word: 'Pinguino', clue: 'Vive al freddo' },
      { word: 'Squalo', clue: 'Fa paura' },
      { word: 'Ape', clue: 'Lavora tutto il giorno' },
      { word: 'Elefante', clue: 'Occupa spazio' },
      { word: 'Zanzara', clue: 'Rovina le serate' },
      { word: 'Cavallo', clue: 'Si può cavalcare' },
      { word: 'Pappagallo', clue: 'Ripete quello che sente' },
      { word: 'Tartaruga', clue: 'Non ha fretta' },
      { word: 'Lupo', clue: 'Si muove in gruppo' },
      { word: 'Piccione', clue: 'Sta in città' },
      { word: 'Delfino', clue: 'Sembra intelligente' },
      { word: 'Ragno', clue: 'Sta negli angoli' },
      { word: 'Criceto', clue: 'Sta in gabbia' },
    ],
  },
  {
    id: 'luoghi',
    name: 'Luoghi',
    entries: [
      { word: 'Spiaggia', clue: 'Ci vai in vacanza' },
      { word: 'Palestra', clue: 'Ci vai con buoni propositi' },
      { word: 'Aeroporto', clue: 'Si aspetta parecchio' },
      { word: 'Supermercato', clue: 'Ci si va ogni settimana' },
      { word: 'Ospedale', clue: 'Nessuno ci va volentieri' },
      { word: 'Montagna', clue: 'Bisogna salire' },
      { word: 'Cinema', clue: 'Si sta al buio' },
      { word: 'Scuola', clue: 'Ci sono ricordi' },
      { word: 'Discoteca', clue: 'Si fa tardi' },
      { word: 'Ufficio', clue: 'Dal lunedì al venerdì' },
      { word: 'Metropolitana', clue: 'Sempre piena' },
      { word: 'Deserto', clue: "Non c'è nessuno" },
      { word: 'Stadio', clue: 'Si urla parecchio' },
      { word: 'Biblioteca', clue: 'Silenzio obbligatorio' },
      { word: 'Parrucchiere', clue: 'Si chiacchiera molto' },
    ],
  },
  {
    id: 'oggetti',
    name: 'Oggetti di casa',
    entries: [
      { word: 'Frigorifero', clue: 'Si apre spesso' },
      { word: 'Divano', clue: 'Difficile alzarsi' },
      { word: 'Spazzolino', clue: 'Due volte al giorno' },
      { word: 'Lavatrice', clue: 'Gira a lungo' },
      { word: 'Ombrello', clue: 'Lo dimentichi sempre' },
      { word: 'Telecomando', clue: 'Sparisce sempre' },
      { word: 'Sveglia', clue: 'Nessuno la ama' },
      { word: 'Specchio', clue: 'Dice la verità' },
      { word: 'Aspirapolvere', clue: 'Fa un gran rumore' },
      { word: 'Calzino', clue: 'Ne manca sempre uno' },
      { word: 'Chiavi', clue: 'Le cerchi di fretta' },
      { word: 'Candela', clue: 'Crea atmosfera' },
      { word: 'Coperta', clue: 'Roba da inverno' },
      { word: 'Forbici', clue: 'Meglio stare attenti' },
      { word: 'Caricabatterie', clue: 'Non se ne ha mai abbastanza' },
    ],
  },
  {
    id: 'film',
    name: 'Film e serie',
    entries: [
      { word: 'Titanic', clue: 'Finisce male' },
      { word: 'Harry Potter', clue: 'Storia di ragazzi' },
      { word: 'Il Signore degli Anelli', clue: 'Un viaggio lunghissimo' },
      { word: 'Shrek', clue: 'Fa ridere i bambini' },
      { word: 'Matrix', clue: 'Bisogna scegliere' },
      { word: 'Jurassic Park', clue: 'Qualcosa va storto' },
      { word: 'Il Padrino', clue: 'Questione di famiglia' },
      { word: 'Frozen', clue: 'Tutti conoscono la canzone' },
      { word: 'Squid Game', clue: 'Si gioca sul serio' },
      { word: 'Breaking Bad', clue: 'Un uomo cambia' },
      { word: 'Stranger Things', clue: 'Roba di ragazzini e mistero' },
      { word: 'Friends', clue: 'Sempre gli stessi divani' },
      { word: 'Avatar', clue: 'Tanto blu' },
      { word: 'La Casa di Carta', clue: 'Tutti vestiti uguali' },
      { word: 'Ritorno al Futuro', clue: 'Questione di tempo' },
    ],
  },
  {
    id: 'sport',
    name: 'Sport e tempo libero',
    entries: [
      { word: 'Calcio', clue: 'Se ne parla troppo' },
      { word: 'Tennis', clue: 'Uno contro uno' },
      { word: 'Nuoto', clue: 'Serve il costume' },
      { word: 'Sci', clue: 'Roba da inverno' },
      { word: 'Yoga', clue: 'Bisogna respirare' },
      { word: 'Scacchi', clue: 'Si pensa molto' },
      { word: 'Maratona', clue: 'Ci vuole fiato' },
      { word: 'Pallavolo', clue: 'Si gioca in squadra' },
      { word: 'Videogiochi', clue: 'Passa il tempo' },
      { word: 'Karaoke', clue: 'Serve coraggio' },
      { word: 'Pesca', clue: 'Ci vuole pazienza' },
      { word: 'Bicicletta', clue: 'Non si dimentica mai' },
      { word: 'Poker', clue: 'Meglio non farsi leggere' },
      { word: 'Boxe', clue: 'Si prendono colpi' },
      { word: 'Surf', clue: 'Bisogna aspettare il momento' },
    ],
  },
]

export const DEFAULT_PACK_IDS = WORD_PACKS.map((pack) => pack.id)
