import type { WordPack } from './types'

/**
 * Le parole, raggruppate per categoria. La categoria è anche l'indizio che legge
 * l'impostore: lo mette sulla strada giusta senza consegnargli la parola.
 * Perché l'indizio valga qualcosa devono essere attive almeno due categorie,
 * altrimenti i giocatori normali sanno già quello che sta leggendo lui.
 */
export const WORD_PACKS: WordPack[] = [
  {
    id: 'cibo',
    name: 'Cibo e bevande',
    entries: [
      'Pizza',
      'Carbonara',
      'Gelato',
      'Caffè',
      'Sushi',
      'Panettone',
      'Birra',
      'Nutella',
      'Insalata',
      'Lasagna',
      'Popcorn',
      'Cornetto',
      'Peperoncino',
      'Vino',
      'Kebab',
    ],
  },
  {
    id: 'animali',
    name: 'Animali',
    entries: [
      'Gatto',
      'Cane',
      'Pinguino',
      'Squalo',
      'Ape',
      'Elefante',
      'Zanzara',
      'Cavallo',
      'Pappagallo',
      'Tartaruga',
      'Lupo',
      'Piccione',
      'Delfino',
      'Ragno',
      'Criceto',
    ],
  },
  {
    id: 'luoghi',
    name: 'Luoghi',
    entries: [
      'Spiaggia',
      'Palestra',
      'Aeroporto',
      'Supermercato',
      'Ospedale',
      'Montagna',
      'Cinema',
      'Scuola',
      'Discoteca',
      'Ufficio',
      'Metropolitana',
      'Deserto',
      'Stadio',
      'Biblioteca',
      'Parrucchiere',
    ],
  },
  {
    id: 'oggetti',
    name: 'Oggetti di casa',
    entries: [
      'Frigorifero',
      'Divano',
      'Spazzolino',
      'Lavatrice',
      'Ombrello',
      'Telecomando',
      'Sveglia',
      'Specchio',
      'Aspirapolvere',
      'Calzino',
      'Chiavi',
      'Candela',
      'Coperta',
      'Forbici',
      'Caricabatterie',
    ],
  },
  {
    id: 'film',
    name: 'Film e serie',
    entries: [
      'Titanic',
      'Harry Potter',
      'Il Signore degli Anelli',
      'Shrek',
      'Matrix',
      'Jurassic Park',
      'Il Padrino',
      'Frozen',
      'Squid Game',
      'Breaking Bad',
      'Stranger Things',
      'Friends',
      'Avatar',
      'La Casa di Carta',
      'Ritorno al Futuro',
    ],
  },
  {
    id: 'sport',
    name: 'Sport e tempo libero',
    entries: [
      'Calcio',
      'Tennis',
      'Nuoto',
      'Sci',
      'Yoga',
      'Scacchi',
      'Maratona',
      'Pallavolo',
      'Videogiochi',
      'Karaoke',
      'Pesca',
      'Bicicletta',
      'Poker',
      'Boxe',
      'Surf',
    ],
  },
]

export const DEFAULT_PACK_IDS = WORD_PACKS.map((pack) => pack.id)

/** Quante categorie servono perché l'indizio dell'impostore dica davvero qualcosa. */
export const MIN_PACKS_FOR_CLUE = 2
