import type { WordPack } from './types'

/**
 * Le parole, raggruppate per categoria. La categoria è anche l'indizio che legge
 * l'impostore: lo mette sulla strada giusta senza consegnargli la parola.
 *
 * Due regole per chi aggiunge roba qui, perché l'indizio funzioni davvero.
 *
 * Le categorie non si devono sovrapporre. Una parola va nella categoria che il
 * tavolo nominerebbe per prima, e in nessun'altra: se il calzino sta fra gli
 * oggetti di casa, l'impostore che legge "Vestiti e accessori" viene mandato fuori
 * strada, e quell'indizio gli ha fatto più male che bene. Per lo stesso motivo la
 * bicicletta sta fra i mezzi di trasporto e non fra gli sport, dove c'è il ciclismo.
 *
 * Perché l'indizio valga qualcosa devono essere attive almeno due categorie,
 * altrimenti i giocatori normali sanno già quello che sta leggendo lui.
 */
export const WORD_PACKS: WordPack[] = [
  {
    id: 'cibo',
    name: 'Cibo e bevande',
    entries: [
      'Pizza',
      'Carbonara',
      'Gelato',
      'Caffè',
      'Sushi',
      'Panettone',
      'Birra',
      'Nutella',
      'Insalata',
      'Lasagna',
      'Popcorn',
      'Cornetto',
      'Peperoncino',
      'Vino',
      'Kebab',
      'Patatine fritte',
      'Tiramisù',
      'Mozzarella',
      'Anguria',
      'Cioccolata calda',
    ],
  },
  {
    id: 'animali',
    name: 'Animali',
    entries: [
      'Gatto',
      'Cane',
      'Pinguino',
      'Squalo',
      'Ape',
      'Elefante',
      'Zanzara',
      'Cavallo',
      'Pappagallo',
      'Tartaruga',
      'Lupo',
      'Piccione',
      'Delfino',
      'Ragno',
      'Criceto',
      'Gabbiano',
      'Serpente',
      'Scoiattolo',
      'Mucca',
      'Gufo',
    ],
  },
  {
    id: 'luoghi',
    name: 'Luoghi',
    entries: [
      'Spiaggia',
      'Palestra',
      'Aeroporto',
      'Supermercato',
      'Ospedale',
      'Montagna',
      'Cinema',
      'Scuola',
      'Discoteca',
      'Ufficio',
      'Metropolitana',
      'Deserto',
      'Stadio',
      'Biblioteca',
      'Parrucchiere',
      'Bosco',
      'Museo',
      'Autogrill',
      'Isola',
      'Cantiere',
    ],
  },
  {
    id: 'oggetti',
    name: 'Oggetti di casa',
    entries: [
      'Frigorifero',
      'Divano',
      'Spazzolino',
      'Lavatrice',
      'Telecomando',
      'Sveglia',
      'Specchio',
      'Aspirapolvere',
      'Chiavi',
      'Candela',
      'Coperta',
      'Forbici',
      'Caricabatterie',
      'Materasso',
      'Tenda',
      'Scopa',
      'Cuscino',
      'Lampadina',
      'Tappeto',
      'Termosifone',
    ],
  },
  {
    id: 'film',
    name: 'Film e serie',
    entries: [
      'Titanic',
      'Harry Potter',
      'Il Signore degli Anelli',
      'Shrek',
      'Matrix',
      'Jurassic Park',
      'Il Padrino',
      'Frozen',
      'Squid Game',
      'Breaking Bad',
      'Stranger Things',
      'Friends',
      'Avatar',
      'La Casa di Carta',
      'Ritorno al Futuro',
      'Il Re Leone',
      'Gomorra',
      'Star Wars',
      'Mare Fuori',
      'Pirati dei Caraibi',
    ],
  },
  {
    id: 'sport',
    name: 'Sport e tempo libero',
    entries: [
      'Calcio',
      'Tennis',
      'Nuoto',
      'Sci',
      'Yoga',
      'Scacchi',
      'Maratona',
      'Pallavolo',
      'Videogiochi',
      'Karaoke',
      'Pesca',
      'Ciclismo',
      'Poker',
      'Boxe',
      'Surf',
      'Basket',
      'Escursione',
      'Giardinaggio',
      'Bowling',
      'Arrampicata',
    ],
  },
  {
    id: 'trasporti',
    name: 'Mezzi di trasporto',
    entries: [
      'Bicicletta',
      'Aereo',
      'Traghetto',
      'Monopattino',
      'Autobus',
      'Motorino',
      'Treno',
      'Taxi',
      'Camion',
      'Mongolfiera',
      'Ambulanza',
      'Gondola',
      'Elicottero',
      'Funivia',
      'Ruspa',
    ],
  },
  {
    id: 'musica',
    name: 'Musica e strumenti',
    entries: [
      'Chitarra',
      'Batteria',
      'Pianoforte',
      'Violino',
      'Concerto',
      'Coro',
      'Tromba',
      'Sanremo',
      'Rap',
      'Fisarmonica',
      'Opera lirica',
      'Ritornello',
      'Dj',
      'Tamburello',
      'Inno nazionale',
    ],
  },
  {
    id: 'vestiti',
    name: 'Vestiti e accessori',
    entries: [
      'Calzino',
      'Cappotto',
      'Cravatta',
      'Occhiali da sole',
      'Scarpe da ginnastica',
      'Costume da bagno',
      'Sciarpa',
      'Jeans',
      'Cappello',
      'Orologio',
      'Zaino',
      'Guanti',
      'Anello',
      'Pigiama',
      'Infradito',
    ],
  },
  {
    id: 'mestieri',
    name: 'Mestieri',
    entries: [
      'Dentista',
      'Pompiere',
      'Cuoco',
      'Maestra',
      'Barista',
      'Idraulico',
      'Astronauta',
      'Giornalista',
      'Contadino',
      'Fotografo',
      'Netturbino',
      'Avvocato',
      'Pilota',
      'Veterinario',
      'Meccanico',
    ],
  },
  {
    id: 'feste',
    name: 'Feste e tradizioni',
    entries: [
      'Natale',
      'Capodanno',
      'Carnevale',
      'Compleanno',
      'Matrimonio',
      'Ferragosto',
      'Halloween',
      'Pasqua',
      'Laurea',
      'San Valentino',
      'Battesimo',
      'Befana',
      'Festa della mamma',
      'Addio al celibato',
      'Primo maggio',
    ],
  },
  {
    id: 'tecnologia',
    name: 'Tecnologia e internet',
    entries: [
      'Wi-Fi',
      'Password',
      'Selfie',
      'Emoji',
      'Podcast',
      'Spam',
      'Videochiamata',
      'Stampante',
      'Bluetooth',
      'Aggiornamento',
      'Cloud',
      'Drone',
      'Qr code',
      'Chatbot',
      'Meme',
    ],
  },
]

export const DEFAULT_PACK_IDS = WORD_PACKS.map((pack) => pack.id)

/** Quante categorie servono perché l'indizio dell'impostore dica davvero qualcosa. */
export const MIN_PACKS_FOR_CLUE = 2
